version: 0.2
phases:
 install:
  runtime-versions:
   python: 3.9
 build: 
  commands:
   - aws cloudformation build
   - export BUCKET=b2bucket2
   - aws cloudformation package --template-file template.yaml --s3-bucket $BUCKET --output-template-file outputtemplate.yaml
artifacts:
 files:
  - "**/*"
